name: redux_saga
maintainer: Bilal Uslu (@bilaluslu)
authors:
  - Bilal Uslu <bilal@bilaluslu.com>
description: redux_saga is a library that aims to make application side effects (i.e. asynchronous things like data fetching and impure things like accessing the browser cache) easier to manage, more efficient to execute, easy to test, and better at handling failures.
homepage: https://github.com/redux_saga/redux_saga.dart
version: 1.0.0


environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  redux: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  fake_async: ^1.1.0